| TC ID           | Module      | Feature                 | Scenario                     | Test Type       | Preconditions / Setup     | Test Data / Input | Steps                                                 | Expected Result                                                                                         | Actual Result | Status | Severity | Execution Date | Comments / Notes |
| --------------- | ----------- | ----------------------- | ---------------------------- | --------------- | ------------------------- | ----------------- | ----------------------------------------------------- | ------------------------------------------------------------------------------------------------------- | ------------- | ------ | -------- | -------------- | ---------------- |
| TC_HOME_001     | Home        | Dashboard Load          | Load Dashboard after login   | Functional / UI | User logged in            |                   | 1\. Login successfully                                | Dashboard shows:<br>\- Greeting text<br>\- Latest Activity<br>\- Job Opportunities<br>\- Earnings graph |               |        | High     |                |                  |
| TC_HOME_002     | Home        | Latest Activity         | Validate displayed items     | Functional      | User has recent activity  |                   | 1\. Login<br>2\. Observe Latest Activity              | Items like Initial Brief, Task List appear correctly                                                    |               |        | Medium   |                |                  |
| TC_HOME_003     | Home        | Job Actions             | Accept a job                 | Functional      | Job available             |                   | 1\. On Dashboard find job card<br>2\. Tap “Accept Job | Job is added to user’s projects                                                                         |               |        | High     |                |                  |
| TC_HOME_004     | Home        | Earnings Graph          | Change duration filters      | UI/Functional   | Dashboard loaded          |                   | 1\. Tap 24h<br>2\. Tap 7d<br>3\. Tap 1m, etc.         | Graph updates accordingly                                                                               |               |        | Medium   |                |                  |
| TC_PROJECT_001  | Projects    | Projects List           | Load all user projects       | Functional/UI   | User logged in            |                   | 1\. Navigate to Projects tab                          | All project circles with initials appear                                                                |               |        | High     |                |                  |
| TC_PROJECT_002  | Projects    | Search                  | Search for a project         | Functional      | At least 1 project exists | Search keyword    | 1\. Tap search bar<br>2\. Enter keyword               | Matching projects displayed                                                                             |               |        | Medium   |                |                  |
| TC_PROJECT_003  | Projects    | Sorting                 | Sort projects alphabetically | Functional      | Projects available        |                   | 1\. Tap Sort menu<br>2\. Select A–Z                   | Projects sorted alphabetically                                                                          |               |        | Low      |                |                  |
| TC_JOBS_001     | Jobs        | Jobs Listing            | Load jobs                    | Functional/UI   | User logged in            |                   | 1\. Navigate to Jobs tab                              | Job cards (company logo, name, rating) appear                                                           |               |        | High     |                |                  |
| TC_JOBS_002     | Jobs        | View Job                | Open job details             | Functional      | Job exists                |                   | 1\. Tap job card                                      | Detailed job page appears                                                                               |               |        | Medium   |                |                  |
| TC_JOBS_003     | Jobs        | Sorting                 | Sort jobs alphabetically     | UI/Functional   | Jobs available            |                   | 1\. Tap Sort<br>2\. Select A–Z                        | Sorted list shown                                                                                       |               |        | Low      |                |                  |
| TC_USERS_001    | Users       | Users Listing           | Load users                   | UI/Functional   | App logged in             |                   | 1\. Go to Users tab                                   | User profile cards shown with:<br>\- Name<br>\- Profession<br>\- Rating<br>\- Profile image             |               |        | High     |                |                  |
| TC_USERS_002    | Users       | View Profile            | Open profile details         | Functional      | User exists               |                   | 1\. Tap any user card                                 | User profile page opens                                                                                 |               |        | Medium   |                |                  |
| TC_CONTRACT_001 | Contractors | Contractors Listing     | Load contractors             | Functional/UI   | User logged in            |                   | 1\. Go to Contractors tab                             | Contractors are listed successfully                                                                     |               |        | High     |                |                  |
|                 |             | View Contractor Profile | Open contractor details      | Functional      | Contractor exists         |                   | 1\. Tap contractor card                               | Contractor profile opens                                                                                |               |        | Medium   |                |                  |
